import { Category, Product, FilterState } from '@/types'

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Desktop PCs',
    slug: 'desktop-pcs',
    description: 'Powerful desktop computers for work and gaming',
    image: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=200&h=200&fit=crop',
    _count: { products: 5 },
  },
  {
    id: 'cat-2',
    name: 'Laptops',
    slug: 'laptops',
    description: 'Portable computing solutions for every need',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=200&h=200&fit=crop',
    _count: { products: 4 },
  },
  {
    id: 'cat-3',
    name: 'Monitors',
    slug: 'monitors',
    description: 'Crystal-clear displays for work and gaming',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=200&h=200&fit=crop',
    _count: { products: 3 },
  },
  {
    id: 'cat-4',
    name: 'Keyboards',
    slug: 'keyboards',
    description: 'Mechanical and membrane keyboards',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&h=200&fit=crop',
    _count: { products: 3 },
  },
  {
    id: 'cat-5',
    name: 'Mice',
    slug: 'mice',
    description: 'Precision gaming and office mice',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=200&h=200&fit=crop',
    _count: { products: 2 },
  },
  {
    id: 'cat-6',
    name: 'Headsets',
    slug: 'headsets',
    description: 'Immersive audio for gaming and calls',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&h=200&fit=crop',
    _count: { products: 2 },
  },
  {
    id: 'cat-7',
    name: 'Graphics Cards',
    slug: 'graphics-cards',
    description: 'High-performance GPUs for gaming and rendering',
    image: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=200&h=200&fit=crop',
    _count: { products: 2 },
  },
  {
    id: 'cat-8',
    name: 'RAM',
    slug: 'ram',
    description: 'High-speed memory modules',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&h=200&fit=crop',
    _count: { products: 2 },
  },
  {
    id: 'cat-9',
    name: 'SSDs',
    slug: 'ssds',
    description: 'Fast solid-state storage solutions',
    image: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=200&h=200&fit=crop',
    _count: { products: 2 },
  },
  {
    id: 'cat-10',
    name: 'Webcams',
    slug: 'webcams',
    description: 'HD and 4K webcams for streaming and calls',
    image: 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=200&h=200&fit=crop',
    _count: { products: 1 },
  },
]

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Corsair K95 RGB Platinum XT Mechanical Keyboard',
    slug: 'corsair-k95-rgb-platinum-xt-mechanical-keyboard',
    description:
      'The CORSAIR K95 RGB PLATINUM XT Mechanical Gaming Keyboard combines premium aesthetics with exceptional performance. Featuring CHERRY MX Blue switches for a satisfying click, 6 dedicated macro keys, and per-key RGB lighting with 19-zone LightEdge.',
    price: 179.99,
    comparePrice: 229.99,
    sku: 'CK95-RGB-MX-BLUE',
    stock: 42,
    brand: 'Corsair',
    rating: 4.7,
    reviewCount: 1284,
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-4',
    category: categories[3],
    tags: ['mechanical', 'rgb', 'gaming', 'cherry mx'],
    colors: ['Black', 'White'],
    images: [
      {
        id: 'img-1-1',
        url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop',
        alt: 'Corsair K95 RGB Keyboard',
        isPrimary: true,
        sortOrder: 0,
      },
      {
        id: 'img-1-2',
        url: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&h=600&fit=crop',
        alt: 'Corsair K95 side view',
        isPrimary: false,
        sortOrder: 1,
      },
    ],
    specs: {
      'Switch Type': 'Cherry MX Blue',
      Interface: 'USB',
      'Backlight': 'RGB per-key',
      'Macro Keys': 6,
      'N-Key Rollover': true,
      Dimensions: '451 x 165 x 35 mm',
      Weight: '1.32 kg',
      'USB Passthrough': true,
    },
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Logitech G502 HERO High Performance Gaming Mouse',
    slug: 'logitech-g502-hero-gaming-mouse',
    description:
      'The Logitech G502 HERO features the most advanced HERO 25K gaming sensor available. With adjustable weight system, 11 programmable buttons, and LIGHTSYNC RGB, this mouse offers unmatched performance for competitive gaming.',
    price: 69.99,
    comparePrice: 89.99,
    sku: 'LG502-HERO-BLK',
    stock: 87,
    brand: 'Logitech',
    rating: 4.8,
    reviewCount: 3521,
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-5',
    category: categories[4],
    tags: ['gaming mouse', 'rgb', 'programmable', 'logitech'],
    colors: ['Black'],
    images: [
      {
        id: 'img-2-1',
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop',
        alt: 'Logitech G502 HERO',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Sensor: 'HERO 25K',
      DPI: '100–25,600',
      Buttons: 11,
      'Weight Tuning': true,
      'Onboard Memory': '5 profiles',
      Interface: 'USB',
      'Cable Length': '2.1 m',
    },
    createdAt: '2024-05-15T00:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'LG 27GP850-B 27" UltraGear QHD 165Hz Gaming Monitor',
    slug: 'lg-27gp850-b-27-ultragear-qhd-165hz-gaming-monitor',
    description:
      'Experience ultra-smooth gaming with the LG UltraGear 27GP850-B. This 27-inch QHD Nano IPS display delivers 165Hz refresh rate, 1ms response time, and NVIDIA G-Sync compatibility for tear-free gaming.',
    price: 349.99,
    comparePrice: 449.99,
    sku: 'LG-27GP850-B',
    stock: 23,
    brand: 'LG',
    rating: 4.6,
    reviewCount: 892,
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-3',
    category: categories[2],
    tags: ['monitor', 'gaming', 'qhd', '165hz', 'g-sync'],
    images: [
      {
        id: 'img-3-1',
        url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=600&fit=crop',
        alt: 'LG UltraGear Monitor',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      'Panel Type': 'Nano IPS',
      Resolution: '2560 x 1440 (QHD)',
      'Refresh Rate': '165Hz',
      'Response Time': '1ms (GtG)',
      HDR: 'HDR400',
      Ports: 'HDMI 2.0 x2, DisplayPort 1.4 x1, USB 3.0 x2',
      'G-Sync Compatible': true,
      'FreeSync Premium': true,
    },
    createdAt: '2024-04-10T00:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'ASUS ROG Strix G16 Gaming Laptop RTX 4070',
    slug: 'asus-rog-strix-g16-gaming-laptop-rtx-4070',
    description:
      'The ASUS ROG Strix G16 packs the latest Intel Core i9 processor and NVIDIA GeForce RTX 4070 GPU into a 16-inch powerhouse. With 240Hz display, 32GB DDR5 RAM, and 1TB NVMe SSD, it dominates every game.',
    price: 1799.99,
    comparePrice: 2099.99,
    sku: 'ROG-G16-I9-RTX4070',
    stock: 12,
    brand: 'ASUS',
    rating: 4.9,
    reviewCount: 341,
    isFeatured: true,
    isOnSale: true,
    isNew: true,
    status: 'ACTIVE',
    categoryId: 'cat-2',
    category: categories[1],
    tags: ['laptop', 'gaming', 'rtx 4070', 'rog'],
    colors: ['Eclipse Gray', 'Volt Green'],
    images: [
      {
        id: 'img-4-1',
        url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop',
        alt: 'ASUS ROG Strix G16',
        isPrimary: true,
        sortOrder: 0,
      },
      {
        id: 'img-4-2',
        url: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
        alt: 'ROG Strix keyboard',
        isPrimary: false,
        sortOrder: 1,
      },
    ],
    specs: {
      CPU: 'Intel Core i9-14900HX',
      GPU: 'NVIDIA GeForce RTX 4070 8GB',
      RAM: '32GB DDR5-4800',
      Storage: '1TB NVMe PCIe 4.0 SSD',
      Display: '16" FHD+ 240Hz IPS',
      Battery: '90Wh',
      OS: 'Windows 11 Home',
    },
    createdAt: '2024-08-01T00:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'NVIDIA GeForce RTX 4080 Super 16GB',
    slug: 'nvidia-geforce-rtx-4080-super-16gb',
    description:
      'Experience next-gen gaming with the RTX 4080 Super. Featuring 16GB GDDR6X VRAM, DLSS 3, and Ray Tracing, this GPU delivers exceptional 4K gaming performance and creative workstation capabilities.',
    price: 999.99,
    comparePrice: undefined,
    sku: 'RTX-4080S-16GB',
    stock: 8,
    brand: 'NVIDIA',
    rating: 4.8,
    reviewCount: 567,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    status: 'ACTIVE',
    categoryId: 'cat-7',
    category: categories[6],
    tags: ['gpu', 'gaming', 'rtx 4080', '4k'],
    images: [
      {
        id: 'img-5-1',
        url: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&h=600&fit=crop',
        alt: 'RTX 4080 Super',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Architecture: 'Ada Lovelace',
      VRAM: '16GB GDDR6X',
      'CUDA Cores': 10240,
      'Memory Bandwidth': '736 GB/s',
      'TDP': '320W',
      Ports: 'HDMI 2.1a, DisplayPort 1.4a x3',
      'DLSS': '3.5',
      'Ray Tracing': true,
    },
    createdAt: '2024-07-20T00:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Corsair Vengeance DDR5-6000 32GB (2x16GB)',
    slug: 'corsair-vengeance-ddr5-6000-32gb',
    description:
      'Corsair Vengeance DDR5-6000 offers extreme performance with EXPO and XMP 3.0 profiles for easy overclocking. Aluminum heat spreader keeps temperatures low during intensive tasks.',
    price: 109.99,
    comparePrice: 139.99,
    sku: 'CMK32GX5M2E6000C36',
    stock: 65,
    brand: 'Corsair',
    rating: 4.6,
    reviewCount: 422,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-8',
    category: categories[7],
    tags: ['ram', 'ddr5', 'memory', 'corsair'],
    colors: ['Black', 'White'],
    images: [
      {
        id: 'img-6-1',
        url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=600&fit=crop',
        alt: 'Corsair Vengeance DDR5',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Type: 'DDR5',
      Capacity: '32GB (2x16GB)',
      Speed: '6000MHz',
      Latency: 'CL36',
      Voltage: '1.35V',
      'XMP 3.0': true,
      EXPO: true,
    },
    createdAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Samsung 990 Pro 2TB NVMe SSD',
    slug: 'samsung-990-pro-2tb-nvme-ssd',
    description:
      'The Samsung 990 Pro redefines PCIe 4.0 NVMe performance. With sequential read speeds up to 7,450 MB/s and write speeds of 6,900 MB/s, it handles the most demanding workloads effortlessly.',
    price: 159.99,
    comparePrice: 199.99,
    sku: 'MZ-V9P2T0BW',
    stock: 34,
    brand: 'Samsung',
    rating: 4.9,
    reviewCount: 1876,
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-9',
    category: categories[8],
    tags: ['ssd', 'nvme', 'pcie 4.0', 'samsung'],
    images: [
      {
        id: 'img-7-1',
        url: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&h=600&fit=crop',
        alt: 'Samsung 990 Pro SSD',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Capacity: '2TB',
      Interface: 'PCIe 4.0 x4, NVMe 2.0',
      'Sequential Read': '7,450 MB/s',
      'Sequential Write': '6,900 MB/s',
      'Random Read (IOPS)': '1,600,000',
      'Random Write (IOPS)': '1,550,000',
      DRAM: 'Yes',
      TBW: '1,200 TBW',
    },
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'SteelSeries Arctis Nova Pro Wireless Gaming Headset',
    slug: 'steelseries-arctis-nova-pro-wireless-gaming-headset',
    description:
      'The Arctis Nova Pro Wireless offers audiophile-grade Hi-Res audio with dual wireless (2.4GHz + Bluetooth), active noise cancellation, and hot-swap battery system for uninterrupted gaming.',
    price: 329.99,
    comparePrice: 349.99,
    sku: 'SS-ARCTIS-NOVA-PRO-W',
    stock: 19,
    brand: 'SteelSeries',
    rating: 4.7,
    reviewCount: 638,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-6',
    category: categories[5],
    tags: ['headset', 'wireless', 'gaming', 'anc'],
    colors: ['Black', 'White'],
    images: [
      {
        id: 'img-8-1',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
        alt: 'SteelSeries Arctis Nova Pro',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      'Driver Size': '40mm',
      'Frequency Response': '10–40,000 Hz',
      Connectivity: '2.4GHz Wireless + Bluetooth 5.0',
      'Battery Life': '22h (per battery)',
      'Hot-Swap Battery': true,
      ANC: true,
      Microphone: 'Retractable ClearCast',
      Weight: '338g',
    },
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'prod-9',
    name: 'Acer Predator Orion 7000 Gaming Desktop RTX 4090',
    slug: 'acer-predator-orion-7000-gaming-desktop-rtx-4090',
    description:
      'The Predator Orion 7000 is a true powerhouse featuring the Intel Core i9-13900K and NVIDIA RTX 4090 in a liquid-cooled chassis. Conquer any game at 4K with maximum settings.',
    price: 3499.99,
    comparePrice: 3999.99,
    sku: 'PO7-690-PRED-RTX4090',
    stock: 5,
    brand: 'Acer',
    rating: 4.9,
    reviewCount: 127,
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-1',
    category: categories[0],
    tags: ['desktop', 'gaming pc', 'rtx 4090', 'predator'],
    colors: ['Black'],
    images: [
      {
        id: 'img-9-1',
        url: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=600&h=600&fit=crop',
        alt: 'Acer Predator Orion 7000',
        isPrimary: true,
        sortOrder: 0,
      },
      {
        id: 'img-9-2',
        url: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=600&h=600&fit=crop',
        alt: 'Predator interior',
        isPrimary: false,
        sortOrder: 1,
      },
    ],
    specs: {
      CPU: 'Intel Core i9-13900K',
      GPU: 'NVIDIA GeForce RTX 4090 24GB',
      RAM: '64GB DDR5-5600',
      Storage: '2TB PCIe 5.0 SSD + 2TB HDD',
      Cooling: '360mm AIO Liquid Cooler',
      PSU: '1000W 80+ Gold',
      OS: 'Windows 11 Home',
    },
    createdAt: '2024-06-20T00:00:00Z',
  },
  {
    id: 'prod-10',
    name: 'Dell UltraSharp U2723D 27" 4K USB-C Monitor',
    slug: 'dell-ultrasharp-u2723d-27-4k-usb-c-monitor',
    description:
      'The Dell UltraSharp U2723D features IPS Black technology for deeper blacks, 4K resolution, USB-C 90W power delivery, and Thunderbolt 4 connectivity — perfect for professionals.',
    price: 699.99,
    comparePrice: 799.99,
    sku: 'DELL-U2723D',
    stock: 18,
    brand: 'Dell',
    rating: 4.7,
    reviewCount: 489,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-3',
    category: categories[2],
    tags: ['monitor', '4k', 'usb-c', 'professional'],
    images: [
      {
        id: 'img-10-1',
        url: 'https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?w=600&h=600&fit=crop',
        alt: 'Dell UltraSharp U2723D',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      'Panel Type': 'IPS Black',
      Resolution: '3840 x 2160 (4K)',
      'Refresh Rate': '60Hz',
      'Color Coverage': '100% sRGB, 98% DCI-P3',
      Ports: 'USB-C 90W, Thunderbolt 4, HDMI 2.0, DP 1.4',
      'USB Hub': 'USB-C x2, USB-A x3',
      Pivot: true,
    },
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'prod-11',
    name: 'Razer BlackWidow V4 Pro Wireless Mechanical Keyboard',
    slug: 'razer-blackwidow-v4-pro-wireless-mechanical-keyboard',
    description:
      'The BlackWidow V4 Pro brings wireless freedom to the legendary BlackWidow line. Features Razer Yellow (linear) switches, tri-mode connectivity, and Chroma RGB underglow.',
    price: 229.99,
    comparePrice: undefined,
    sku: 'RZ03-BWDV4P-R3U1',
    stock: 28,
    brand: 'Razer',
    rating: 4.5,
    reviewCount: 213,
    isFeatured: false,
    isOnSale: false,
    isNew: true,
    status: 'ACTIVE',
    categoryId: 'cat-4',
    category: categories[3],
    tags: ['keyboard', 'wireless', 'mechanical', 'rgb'],
    colors: ['Black'],
    images: [
      {
        id: 'img-11-1',
        url: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&h=600&fit=crop',
        alt: 'Razer BlackWidow V4 Pro',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      'Switch Type': 'Razer Yellow (Linear)',
      Connectivity: 'Tri-mode (2.4GHz / Bluetooth / USB)',
      'Battery Life': '200h (Bluetooth)',
      Backlight: 'Chroma RGB per-key + underglow',
      'N-Key Rollover': true,
      'Media Keys': 'Dedicated dial + keys',
      Weight: '1.47 kg',
    },
    createdAt: '2024-09-01T00:00:00Z',
  },
  {
    id: 'prod-12',
    name: 'Logitech C922 Pro HD Stream Webcam',
    slug: 'logitech-c922-pro-hd-stream-webcam',
    description:
      'The Logitech C922 Pro HD captures full 1080p at 30fps or 720p at 60fps. With background replacement and dual stereo microphones, it is the go-to webcam for streamers and content creators.',
    price: 99.99,
    comparePrice: 129.99,
    sku: 'LOG-C922-PRO',
    stock: 53,
    brand: 'Logitech',
    rating: 4.4,
    reviewCount: 2341,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-10',
    category: categories[9],
    tags: ['webcam', 'streaming', '1080p', 'logitech'],
    images: [
      {
        id: 'img-12-1',
        url: 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=600&h=600&fit=crop',
        alt: 'Logitech C922 Pro Webcam',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Resolution: '1080p@30fps / 720p@60fps',
      'Field of View': '78°',
      Autofocus: true,
      Microphone: 'Dual stereo mics',
      'Background Replacement': true,
      Interface: 'USB 2.0',
      Mount: 'Tripod / monitor clip',
    },
    createdAt: '2023-11-10T00:00:00Z',
  },
  {
    id: 'prod-13',
    name: 'MSI MAG Infinite S3 Gaming Desktop RTX 4060',
    slug: 'msi-mag-infinite-s3-gaming-desktop-rtx-4060',
    description:
      'The MSI MAG Infinite S3 delivers excellent 1080p and 1440p gaming with an Intel Core i7-14700F and RTX 4060. The compact mid-tower design includes Mystic Light RGB and tool-less access.',
    price: 1099.99,
    comparePrice: 1299.99,
    sku: 'MAG-INF-S3-I7-RTX4060',
    stock: 14,
    brand: 'MSI',
    rating: 4.5,
    reviewCount: 189,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-1',
    category: categories[0],
    tags: ['desktop', 'gaming pc', 'rtx 4060', 'msi'],
    colors: ['Black'],
    images: [
      {
        id: 'img-13-1',
        url: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=600&h=600&fit=crop',
        alt: 'MSI MAG Infinite S3',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      CPU: 'Intel Core i7-14700F',
      GPU: 'NVIDIA GeForce RTX 4060 8GB',
      RAM: '16GB DDR5',
      Storage: '512GB NVMe SSD',
      PSU: '650W 80+ Bronze',
      OS: 'Windows 11 Home',
    },
    createdAt: '2024-04-15T00:00:00Z',
  },
  {
    id: 'prod-14',
    name: 'HyperX Cloud Alpha Wireless Gaming Headset',
    slug: 'hyperx-cloud-alpha-wireless-gaming-headset',
    description:
      'The HyperX Cloud Alpha Wireless delivers legendary HyperX comfort with up to 300 hours of battery life. Dual Chamber drivers reduce distortion for crystal-clear audio at any volume.',
    price: 159.99,
    comparePrice: 199.99,
    sku: 'HHSC1A-BA-BK/G',
    stock: 31,
    brand: 'HyperX',
    rating: 4.6,
    reviewCount: 1102,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-6',
    category: categories[5],
    tags: ['headset', 'wireless', 'gaming', 'hyperx'],
    colors: ['Black', 'Red'],
    images: [
      {
        id: 'img-14-1',
        url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop',
        alt: 'HyperX Cloud Alpha Wireless',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      'Driver Size': '50mm',
      'Frequency Response': '15–21,000 Hz',
      Connectivity: '2.4GHz Wireless',
      'Battery Life': '300h',
      Microphone: 'Detachable noise-cancelling',
      Weight: '335g',
    },
    createdAt: '2023-12-01T00:00:00Z',
  },
  {
    id: 'prod-15',
    name: 'AMD Radeon RX 7900 XTX 24GB',
    slug: 'amd-radeon-rx-7900-xtx-24gb',
    description:
      'The Radeon RX 7900 XTX leads AMD\'s RDNA 3 lineup with 24GB GDDR6 VRAM, DisplayPort 2.1, and AV1 hardware encoding. Ideal for 4K gaming and content creation at ultra settings.',
    price: 879.99,
    comparePrice: 999.99,
    sku: 'RX7900XTX-24G',
    stock: 11,
    brand: 'AMD',
    rating: 4.7,
    reviewCount: 334,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-7',
    category: categories[6],
    tags: ['gpu', 'gaming', 'rx 7900', '4k', 'amd'],
    images: [
      {
        id: 'img-15-1',
        url: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&h=600&fit=crop',
        alt: 'AMD Radeon RX 7900 XTX',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Architecture: 'RDNA 3',
      VRAM: '24GB GDDR6',
      'Compute Units': 96,
      'Memory Bandwidth': '960 GB/s',
      TDP: '355W',
      Ports: 'DP 2.1 x2, HDMI 2.1 x1, USB-C x1',
      'AV1 Encode': true,
    },
    createdAt: '2024-05-01T00:00:00Z',
  },
  {
    id: 'prod-16',
    name: 'G.Skill Trident Z5 RGB DDR5-7200 64GB (2x32GB)',
    slug: 'gskill-trident-z5-rgb-ddr5-7200-64gb',
    description:
      'G.Skill Trident Z5 RGB pushes DDR5 memory to its limits with 7200MHz speed, individual addressable RGB lighting, and Samsung B-die ICs. Designed for extreme overclockers and content creators.',
    price: 249.99,
    comparePrice: undefined,
    sku: 'F5-7200J3646G32GX2-TZ5RK',
    stock: 22,
    brand: 'G.Skill',
    rating: 4.8,
    reviewCount: 156,
    isFeatured: false,
    isOnSale: false,
    isNew: true,
    status: 'ACTIVE',
    categoryId: 'cat-8',
    category: categories[7],
    tags: ['ram', 'ddr5', 'rgb', 'overclocking'],
    colors: ['Black', 'Silver', 'White'],
    images: [
      {
        id: 'img-16-1',
        url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=600&fit=crop',
        alt: 'G.Skill Trident Z5 RGB',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Type: 'DDR5',
      Capacity: '64GB (2x32GB)',
      Speed: '7200MHz',
      Latency: 'CL36-45-45-115',
      Voltage: '1.4V',
      'XMP 3.0': true,
      RGB: 'Individual addressable',
    },
    createdAt: '2024-08-15T00:00:00Z',
  },
  {
    id: 'prod-17',
    name: 'WD Black SN850X 4TB NVMe SSD with Heatsink',
    slug: 'wd-black-sn850x-4tb-nvme-ssd-heatsink',
    description:
      'The WD Black SN850X with heatsink maximizes performance for PS5 and PC. With 7,300 MB/s read speeds and Game Mode 2.0, this 4TB SSD gives you the space and speed you need.',
    price: 319.99,
    comparePrice: 379.99,
    sku: 'WDS400T2XHE',
    stock: 28,
    brand: 'Western Digital',
    rating: 4.8,
    reviewCount: 723,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-9',
    category: categories[8],
    tags: ['ssd', 'nvme', 'ps5', 'pcie 4.0'],
    images: [
      {
        id: 'img-17-1',
        url: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&h=600&fit=crop',
        alt: 'WD Black SN850X',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Capacity: '4TB',
      Interface: 'PCIe 4.0 x4, NVMe 1.4',
      'Sequential Read': '7,300 MB/s',
      'Sequential Write': '6,600 MB/s',
      Heatsink: true,
      'PS5 Compatible': true,
      TBW: '2,400 TBW',
    },
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'prod-18',
    name: 'Lenovo Legion 7i Gen 9 16" Gaming Laptop RTX 4080',
    slug: 'lenovo-legion-7i-gen-9-16-gaming-laptop-rtx-4080',
    description:
      'The Legion 7i Gen 9 combines an Intel Core i9-14900HX and RTX 4080 in a 16-inch chassis with a stunning 240Hz Mini LED display. The Coldfront 5.0 cooling system keeps performance peak.',
    price: 2299.99,
    comparePrice: 2599.99,
    sku: 'LEG7I-G9-I9-RTX4080',
    stock: 9,
    brand: 'Lenovo',
    rating: 4.8,
    reviewCount: 198,
    isFeatured: false,
    isOnSale: true,
    isNew: true,
    status: 'ACTIVE',
    categoryId: 'cat-2',
    category: categories[1],
    tags: ['laptop', 'gaming', 'rtx 4080', 'legion'],
    colors: ['Titanium', 'Glacier White'],
    images: [
      {
        id: 'img-18-1',
        url: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
        alt: 'Lenovo Legion 7i Gen 9',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      CPU: 'Intel Core i9-14900HX',
      GPU: 'NVIDIA GeForce RTX 4080 12GB',
      RAM: '32GB DDR5-5600',
      Storage: '1TB PCIe 5.0 NVMe SSD',
      Display: '16" QHD+ 240Hz Mini LED',
      Battery: '99.9Wh',
      OS: 'Windows 11 Home',
    },
    createdAt: '2024-09-05T00:00:00Z',
  },
  {
    id: 'prod-19',
    name: 'Alienware Aurora R16 Gaming Desktop RTX 4090',
    slug: 'alienware-aurora-r16-gaming-desktop-rtx-4090',
    description:
      'Alienware Aurora R16 sets the benchmark with Intel Core i9-14900KF and RTX 4090 in the iconic Legend ID chassis. Liquid cooling, tool-less access, and AlienFX RGB deliver maximum performance.',
    price: 3999.99,
    comparePrice: undefined,
    sku: 'AW-AURORA-R16-I9-4090',
    stock: 4,
    brand: 'Dell',
    rating: 4.9,
    reviewCount: 89,
    isFeatured: false,
    isOnSale: false,
    isNew: true,
    status: 'ACTIVE',
    categoryId: 'cat-1',
    category: categories[0],
    tags: ['desktop', 'gaming pc', 'rtx 4090', 'alienware'],
    colors: ['Dark Side of the Moon', 'Lunar Light'],
    images: [
      {
        id: 'img-19-1',
        url: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=600&h=600&fit=crop',
        alt: 'Alienware Aurora R16',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      CPU: 'Intel Core i9-14900KF',
      GPU: 'NVIDIA GeForce RTX 4090 24GB',
      RAM: '64GB DDR5',
      Storage: '2TB NVMe PCIe 4.0 SSD',
      Cooling: '420mm AIO Liquid Cooler',
      PSU: '1350W 80+ Gold',
      OS: 'Windows 11 Home',
    },
    createdAt: '2024-09-20T00:00:00Z',
  },
  {
    id: 'prod-20',
    name: 'Razer DeathAdder V3 HyperSpeed Wireless Mouse',
    slug: 'razer-deathadder-v3-hyperspeed-wireless-mouse',
    description:
      'The DeathAdder V3 HyperSpeed features Razer HyperSpeed Wireless (2.4GHz + Bluetooth), the Focus X 26K optical sensor, and ultra-lightweight 63g design — built for competitive play.',
    price: 79.99,
    comparePrice: 99.99,
    sku: 'RZ01-DAV3HS-R3U1',
    stock: 44,
    brand: 'Razer',
    rating: 4.6,
    reviewCount: 782,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    status: 'ACTIVE',
    categoryId: 'cat-5',
    category: categories[4],
    tags: ['mouse', 'wireless', 'gaming', 'lightweight'],
    colors: ['Black', 'White'],
    images: [
      {
        id: 'img-20-1',
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop',
        alt: 'Razer DeathAdder V3 HyperSpeed',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    specs: {
      Sensor: 'Focus X 26K',
      DPI: '100–26,000',
      Buttons: 5,
      Connectivity: 'HyperSpeed 2.4GHz + Bluetooth',
      'Battery Life': '300h (BT mode)',
      Weight: '63g',
      Switches: 'Razer Optical Gen-3',
    },
    createdAt: '2024-07-10T00:00:00Z',
  },
]

// Helper functions
export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category.slug === categorySlug)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  )
}

export function filterProducts(
  prods: Product[],
  filters: Partial<FilterState>
): Product[] {
  return prods.filter((p) => {
    if (filters.categories && filters.categories.length > 0) {
      if (!filters.categories.includes(p.category.slug)) return false
    }
    if (filters.brands && filters.brands.length > 0) {
      if (!filters.brands.includes(p.brand)) return false
    }
    if (filters.minPrice !== undefined && p.price < filters.minPrice) return false
    if (filters.maxPrice !== undefined && p.price > filters.maxPrice) return false
    if (filters.minRating !== undefined && p.rating < filters.minRating) return false
    if (filters.inStock && p.stock === 0) return false
    if (filters.isOnSale && !p.isOnSale) return false
    if (filters.isNew && !p.isNew) return false
    return true
  })
}

export function sortProducts(prods: Product[], sort: string): Product[] {
  const sorted = [...prods]
  switch (sort) {
    case 'price-asc':
      return sorted.sort((a, b) => a.price - b.price)
    case 'price-desc':
      return sorted.sort((a, b) => b.price - a.price)
    case 'rating':
      return sorted.sort((a, b) => b.rating - a.rating)
    case 'newest':
      return sorted.sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
      )
    case 'name-asc':
      return sorted.sort((a, b) => a.name.localeCompare(b.name))
    default:
      return sorted.sort((a, b) => (b.isFeatured ? 1 : 0) - (a.isFeatured ? 1 : 0))
  }
}

export const uniqueBrands = [...new Set(products.map((p) => p.brand))].sort()
export const maxProductPrice = Math.max(...products.map((p) => p.price))
